name: Git metadata

on:
  workflow_call:
    outputs:
      semver:
        description: 'The (next) Semantic version of this commit'
        value: ${{ jobs.metadata.outputs.semver }}
      shortSHA:
        description: 'Short SHA'
        value: ${{ jobs.metadata.outputs.shortSHA }}

jobs:
  metadata:
    runs-on: ubuntu-latest
    outputs:
      semver: ${{ steps.calculate-metadata.outputs.semver }}
      shortSHA: ${{ steps.calculate-metadata.outputs.shortSHA }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: install git-describe
        run: npm install @contiamo/git-describe

      - name: Calcuation Metadata
        uses: actions/github-script@v7
        id: calculate-metadata
        with:
          script: |
            const { getSemanticVersion } = require('@contiamo/git-describe');

            let sha = '';
            try {
              // truncate the SHA to 7 characters
              sha = context.sha.slice(0, 7);

              core.setOutput('shortSHA', sha);
            } catch (error) {
              const msg = error instanceof Error ? error.message : String(error);
              core.setFailed(msg);
            }

            try {
              const regex = /\+/i;
              const semver = getSemanticVersion();
              core.setOutput('semver', semver.replace(regex, '.'));
            } catch (error) {
              const msg = error instanceof Error ? error.message : String(error);
              core.warning(msg);
              core.setOutput('semver', sha);
            }

      - name: Echo Outputs
        run: |
          echo "Short SHA: ${{ steps.calculate-metadata.outputs.shortSHA }}"
          echo "Semantic Version: ${{ steps.calculate-metadata.outputs.semver }}"
